#S2
#Titel Grundlagen - Inhalt
#Logo gadget32:pinsel/ag.grundlagen
#Font topaz 8
#Y+90
#C10
"Nach   inoffiziellen   Infos
 sind auch  schon UFOs gelan-
 det, KS 4.0 ist rausgekommen
 und Dr. Kittel ist Model bei
 Joop."
   -- Thorsten Stocksmeier in
     "de.comp.sys.amiga.misc"
#Spaltenende
#Y+27
#C31
Das neue Multimediarecht
#C21

Einleitung ..............   1
Das IuKD-Gesetz .........  10
Der MD-Staatsvertrag .... 126
