#S2
#Titel Grundlagen - Inhalt
#Logo gadget38:pinsel/ag.grundlagen
#Font topaz 8
#Y+20
#C10
"Ich  bin  der Meinung,  dass
 Deutschland  zum  Exportland
 Nummer   Eins   für   Organe
 werden  kann.  Die Rohstoff-
 ressourcen sind enorm."
        -- Michael Deutsch in
         "de.alt.geschichten"
#Spaltenende
#Y+140
#C31
Jazz
#C21

Growl (1) ...............   1
Growl (2) ...............   7
Growl (3) ...............  14
Musik und Gesellschaft ..  20
