·
¹f.mod³
°
»





         ½01.         Secret Island (Mr.Pixel/Impulse)            7p.
         ¼02.     Voyage in Storm theme  (Mr.Pixel/Impulse)       6p.
         03.               Message (Scream)                      5p.
                   If I had a piano (Mr.Pixel/Impulse)           5p.
                   Turmixmachine 2 (Bruce/ex-Cerberos)           5p.
                     Tenth Power (Mr.Pixel/Impulse)              5p.
                        Cyclotron (Pat/Frame 18)                 5p.
         04.          Remember to me (Shamen/CDi.)               4p.
                  Il Balerino Di Jazz (Petroff/Absolute!)        4p.
                      Mekkmester (Bruce/ex-Cerberos)             4p.
                            All by Sly Spy                       4p.
                        Stars (Anchor/Therapy)                   4p.
         05.        Eperpudingpor (Bruce/ex-Cerberos)            2p.
                         Atomos (Shamen/CDi.)                    2p.
  