 ¹F.Sas³
 ¹AC.Women³
 °




»



 Az    ¾iráni¼   nagykövetséget,   amely
Londonban  a  Princes  Gate  16.  szám
alatt  volt,  szemben  a Hyde Parkkal,
1980   április  30-án,  szerdán  11.30
órakor  kerítette  hatalmába a három 9
mm-es  automata  pisztollyal, egy 0.38
hüvelykes  revolverrel,  két  9  mm-es
géppisztollyal    és    néhány   kínai
gyártmányú               kézigránáttal
felfegyverzett   hat  terrorista.   Az
akcióban  közvetlenül hat személy vett
részt:   Oan,  a vezér (27 éves) és öt
másik,  mindannyian  a húszas éveikben
jártak.    Valamennyien  Arabisztánból
jöttek,  amely  Iránnak egy Teherántól
kb.   400  mérföldre  esõ területe, és
hosszú  ideig ellenállt az indoeurópai
északiak   uralmának.    Nagy   részük
támogatta a Khomeini Ajatollah vezette
hatalomátvételt a sah ellenében.
 A    terroristák   egy ½  Demokratikus
Forradalmi     Mozgalom     Arabisztán
Felszabadításáért     (DRMLA)¼    nevû,

»









marxista-leninista           csoportot
képviseltek,     amelynek    központja
Líbiában    mûködött,    célja   pedig
Arabisztán     autonómiájának     (nem
függetlenségének) kivívása volt.
 A  támadás  idején  az  épületben  29
személy   tartózkodott:    négy   brit
állampolgár,  valamint  22 iráni férfi
és  nõ,  akik  közül  hárman  az  elsõ
percekben elmenekültek.  A terroristák
követelése  kezdetben az volt, hogy az
iráni  hatóságok  bocsássanak szabadon
91,     Arabisztánban     bebörtönzött
foglyot.    A   határidõt   május  1.,
csütörtök 12.00 órában hagyták meg, és
a  terroristák még az éjszaka folyamán
felvették a kapcsolatot a rendõrséggel
és a médiákkal.
 Szerda  éjjel  egy  beteg  iráni  nõt
szabadon  engedtek, majd másnap reggel
egy   beteg  angol  férfit.   Az  elsõ
határidõt kitolták, amikor a rendõrség
a  terroristák üzenetét közvetítette a
sajtónak, és a második határidõ (14.00
óra)  is  mindkét  oldalon megmozdulás
nélkül zajlott le.
 Péntek         reggelig        számos
kapcsolatfelvétel       történt      a
terroristák  és  a  rendõrség  között,
közvetlenül  vagy közvetítõk által, és
most  már  a  túszok  életét fenyegetõ
megjegyzések      is     elhangzottak.
Szombaton  két túszt szabadon engedtek
annak  fejében, hogy a rádió közvetíti
a       követeléseket       tartalmazó
nyilatkozatot.   Az egyik túszt a kora
esti  órákban engedték el, majd miután
a BBC 21.00 órás híreiben szóról szóra
beolvasták  a  nyilatkozatot,  a másik
túszt is szabadon engedték.
 Vasárnap  a  brit  kormány  több arab
nagykövettel megtárgyalta a helyzetet,
ám  nem  tudtak  megegyezni  a  krízis
megoldását   célzó   szerepükben.    A
nagykövetség  épületében  a változások
nélküli  nap  legnagyobb  eseménye  az
volt,    hogy    az   egyik   súlyosan
megbetegedett   iráni  túszt  szabadon
engedték.
 Hétfõn    a   terroristák   láthatóan
idegesebbek lettek, és a két brit túsz
és  a rendõrök között lezajlott, emelt
hangú    vita   sem   csökkentette   a
feszültséget.  13.30 körül Oan türelme
láthatóan elfogyott, és a rendõrséggel
lezajlott  beszélgetése  alatt lelõtte
Albas  Lavasanit  a nagykövetség egyik
alkalmazottját.      Ez     volt     a
fordulópont.   Minden kétség eloszlott
afelõl,  hogy lelõttek valakit, amikor
a    követség   ajtaján   kitolták   a
holttestet.    Az  elsõ  napon  a  SAS
katonák  megtekintették  a  helyszint,
majd      az     egy-két     mérföldre
lévõ laktanyában  várakoztak.   A  SAS
készenlétben   állt,   amikor  a  brit
törvényes   gyakorlatnak   megfelelõen
felkérte  õket  a rendõrség a probléma
megoldására.
 A  terv  az volt, hogy csak 12 embert
használnak  szokásos négy-négy fõs SAS
csapatokban; két csapat támadott volna
hátulról,  kötélen  ereszkedve  le  az
erkélyrõl,  az  elsõ  a földszintig, a
második    pedig   az   elsõ   emeleti
erkélyre.    Mindkettõ   betört  volna
ablakkeret-robbantókkal   vagy   nyers
erõvel.    A  harmadik  csapat  a  ház
homlokzati  részén, a Princes Gate 15.
számú  házról  jött  volna  át.  Amint
bejutottak az épületbe, minél elõbb el
kellet  jutniuk  a  túszokhoz  mielõtt
bajuk esne.
 Mindent     megtettek    a    támadás
ütõerejének  növelése érdekében.  A 12
SAS-katona   talpig   fekete  overálba
öltözött,  fekete  gázálarcot viseltek
és  ABV  csukját,  ami  tûzálló  volt.
1.2x0.6   m   méretû  keretrobbantókat
használták  a  behatolásra,  majd  ezt
követték a Flesh-Bang bénító gránátok,
amik    CS   gázt   tartalmaztak.    A
robbanások,  a  zaj,  a füst, az akció
gyorsasága,    a   katonák   fenyegetõ
külseje  mind arra volt hivatott, hogy
elbizonytalanítsa   és   megzavarja  a
terroristákat.
 Pontosan 19.25-kor a hátsó támadó erõ
tagjai  átlépték  a  tetõ  peremét  és
leereszkedtek.   Az  elsõ  kettõ  gond
nélkül  leereszkedett mindkét kötélen,
ám   a   harmadik   pár   egyik  tagja
beszorult.    A   homlokzati   oldalon
SAS-katonák  jelentek meg a 15.  számú
ház    erkélyén,    és   átmásztak   a
nagykövetség     épületére.      Ezzel
egyidõben  a rendõrség szóval tartotta
a   terroristákat,   és   a   kritikus
pillanatban,   amikor   a  SAS-katonák
behatoltak,  elvonta a figyelmüket.  A
bénító    gránátok   felrobbantak,   a
világítás  kialudt,  hatalmas  zaj  és
látszólagos  zûrzavar  keletkezett.  A
nagykövetség    egyes   részei   tüzet
fogtak.
 A   SAS   emberei   végigsöpörtek   a
követségen.   Két  terroristát azonnal
eltaláltak   és   megöltek.    Egyikük
elkezdte  lövöldözni  a  túszokat  egy
emeleti helyiségben, ám megállították,
miután   néhány   sebesülést  okozott.
Néhány  percen  belül  a hat fegyveres
közül   öt   halott  volt;  a  hatodik
megpróbált  elbújni  a  túszok között.
Az   összes   túlélõt   leterelték  az
udvarra, ahol a fennmaradó terroristát
felismerték     és     letartóztatták.
Egyetlen  túsz  sem  halt meg az akció
során,    amely    kimagasló    sikert
jelentett  a  nyugat terrorizmus ellen
folytatott küzdelmében.

 Forrás:

    David Miller-Gerard Ridefort:
       Korszerû Elitalakulatok


                         Folyt. köv.

 Ui.:   A  cikk  megírása után történt
meg   az,  amire  hónapokig  vártak  a
médiák  világszerte.   A  Tupak  Amaru
terrorszervezet több hónapos uralmának
vetett  véget  a perui katonaság egyik
részlege.   A  dolog  apropója, hogy a
katonákat  az angol SAS készítette fel
a   feladatra.    Pár   héttel   elõbb
megpróbáltak  már bejutni a követségre
úgy,    hogy   alagutat   fúrtak.    A
terroristák   az   utolsó  pillanatban
vették    észre   a   cselt,   majdnem
megnyalták.


                 ½Skin

         ¾AMIGA RULES FOREVER¼

           Tomasics József
             Nagykanizsa
              Attila 6/b
                 8800