document.write ('<td bgcolor="#eeeeee" valign="top" width="25%" background="../gfx/back0.jpg">',
'<table width="100%" border="0" cellspacing="1" cellpadding="5"><tr>',
'<td align="center" bgcolor="grey" background="../gfx/back1.png"><font size="2" color="yellow"><b>Н а ш и &nbsp; д р у з ь я</b></font></td>',
'</tr><tr><td>',
'<p align="center"><a href="http://www.amiga.org.ru/"><img src="../gfx/page/amiorg.jpg" alt="Amiga Information Center" width="142" height="50" border="1"><br>www.amiga.org.ru</a><br><br>',
'<a href="http://www.amirus.org.ru/"><img src="../gfx/page/amirus.jpg" alt="AmiRus" width="125" height="42" border="1"><br>www.amirus.org.ru</a><br><br>',
'<a href="http://poweramiga.com.ru/"><img src="../gfx/page/power5.jpg" alt="team Power Amiga" width="120" height="90" border="1"><br>www.poweramiga.com.ru</a></p>',
'<tr><td align="center" bgcolor="grey" background="../gfx/back1.png"><font size="2" color="yellow"><b>С т о и т &nbsp; п о с е т и т ь</b></font></td>',
'</tr>',
'<tr><td><p align="center">',
'<font size="-1"><a href="http://www.ann.lu/">Amiga Network News</a><br>',
'<a href="http://www.amiga-news.de/en/">Amiga News DE</a><br>',
'<a href="http://www.morphos-news.de/">MorphOS News</a><br>',
'<a href="http://www.amiga.org/">Amiga Org</a><br>',
'<a href="http://www.amigaworld.net/">Amiga World Net</a><br>',
'<a href="http://www.aminet.net/">Aminet</a><br>',
'<a href="http://www.morphzone.org/">MorphZone</a><br>',
'<a href="http://www.pegasos.org.ru/">Pegasos RU</a><br>',
'<a href="http://www.morphosppc.com/">MorphOS</a><br></font>',
'<br><img src="../gfx/page/nopiracy.gif" alt="Мы против пиратства!" width="100" height="100" border="1">',
'</p></td></tr></table></td></table></td></table>',
'<table width="625" align="center" border="0" cellspacing="1" cellpadding="10" background="../gfx/back.jpg"><tr>',
'<td bgcolor="#f7f7f7" valign="top">',
'<font size="-2"><b>Copyright © 2002-2007 team Dogma - Until the End of Time!<br>All Rights Reserved. Все права защищены.</b><BR><BR>',
'Полное или частичное воспроизведение материалов или графики в любом виде и форме разрешается только с письменного разрешения редакции.<BR>',
'Amiga®, AmigaOS® & Boing® зарегистрированные торговые марки <a href="http://www.amiga.com/">Amiga Inc.</a>, Ravensdale, WA US.<BR>',
'Pegasos® & MorphOS® зарегистрированные торговые марки <a href="http://www.genesi.lu/">Genesi S.а.r.l.</a><BR>',
'<b>Amiga & Pegasos Rules Forever ! Back for the Future !</b></font>',
'</td></tr></table>')
