 News from Alive Mediasoft


Posted by Christian Kemp on 02-Jun-2000 13:35 GMT


After  recent negative press reports on Alive Mediasoft,  both here  on  the
unmoderated  section of ANN,  as well as on amiga-news.de  and  Czech  Amiga
News,  I was surprised to receive an email from Steven Flowers saying:  "Let
me  give  you  somthing  real to right about Alive  will  close  very  soon"
Earlier on,  he already sent an email,  trying to explain the situation with
Goal 2000,  that you can read below.  [ Now,  what is your opinion? Is Alive
good  or bad? What are your experiences with them? Remember,  this  isn't  a
witch hunt, so please don't flame, just state the facts. - CK ]

Hello,
First of all I'm pretty pissed off.  KDH whom I've never dealt with or heard
of  have  taken it upon themselves to distribute emails concerning the  game
Goal  2000  and  their subsequent decision to cease distributing  our  games
becasue  they can't get it to work correctly,  and there is a crack  on  the
front.

Firstly,  we received this enquiry only yesterday and acted immediately with
an explanation and details of how to run the game correctly. However, a two-
hour  turnround on our response was apparantly not good enough  and  they've
felt  the need to go public with this matter with ridiculous accusations  of
it not being Goal 2000, but in fact just the plain old original Goal.

Obviously  this is not the case.  The CD does contain Goal 2000 details  are
below. Anyone having problems can contact us for advice.

What  concerns me most is that people involved in the Amiga market  seem  to
have  nothing  better  to  do than sit around on the  internet  stirring  up
trouble  wherever  possible when they don't  have  a  clue  about  the  real
situation.
This  may  be a part-time hobby to some people,  and quite a few  appear  to
take great pleasure in dragging this market lower than it already is by nit-
picking  and  squabling about everything and anything  they  can  get  their
hands on.

Well  it's  about time that people realised this is a serious business  with
peoples lives and homes on the line. It is not a game.

If  anyone  has concerns about a product,  anyones,  they should address  it
with the company in question first,  then if they are still unhappy with the
outcome  and  feel there is an injustice to the public then fair  enough  go
public, but at least wait for an explanation....

So Goal or Goal 2000?

Did Goal have a cup competition? NO
Did Goal have an aggregate knock-out competition? NO
Did Goal have the British Premier League? NO
Did Goal have a practically inpenetrable goalkeeper? YES
Did Goal have 1999-2000 teams? NO

So, how can Goal 2000 possibly be Goal?

I  don't know what relevance this is but people seem intrigued...  Goal 2000
is not a brand new project.  We've never claimed it to be.  It is in fact an
old  game  called  Goal Championship Cup Edition which never  got  released.
Alive  obtained this,  updated it to the latest leagues and released  it  as
Goal 2000.

Yes,   there is a crack on the front as this was the only version  available
at  the  time  of release,  as is the case nowadays with so many re-releases
and the like.

August  will  see  the  release of a free update for all  Goal  2000  owners
providing  them with all the new teams for next years league and  will  also
eliminate the crack from the front-end.
Last  but  not  least we have been contacted by our German  distributer  GTI
concerning  this.  As our products go through many third  parties  to  reach
Europe,  it took a long time for the news of KDH's dissatisfaction to  reach
us.

As  it  turns  out  we  have  now had response from  GTI  stating  they  are
satisfied  with the product and there is no question of the  origin  of  the
game.   Although this matter is now resolved to everyones satisfaction,   it
would  have  been alot better if people would contact us directly  and  wait
for  a  response before jumping on the band waggon to put everything  up  on
newsgroups.

I'm  sick  of  explaining myself to the whole Amiga community  about  things
that  don't  concern them but some people feel a need to be  arrogant  so  I
must address them.

The  customer  who bought Goal 2000 from us and has had trouble  running  it
has  indeed  emailed  us  a few days ago about this.   However,   he's  only
bothered  to  email Jennie who is now on maternity leave and only  gets  her
mail  a  few  times a week.  Alive have several emails including a technical
support one for these exact type of problems.  There's also the phone,   yet
he's never bothered trying any of these.  He's now had a response explaining
where's  he's going wrong,  but yet again news of this "problem" is  already
circulating  around the news groups.  There's really no  need  for  this  is
there?

Bottom  line is,  this kind of pettiness will stop the public buying Alive's
games - result being no more Alive mediasoft....

Now  KDH have stopped selling Alive's products,  you all know where to  come
for Elite 3 now don't you? He! He! He!

ALIVE mediasoft
Steven Flowers
The Pulse Editor

