#S2
#Titel Grundlagen - Inhalt
#Logo gadget27:pinsel/ag.grundlagen
#Font topaz 8
#C10
#Y+90
 "Eigentlich  ist  der  große
  Lauschangriff  ein Geschenk
  für  die  Bürger   aus  den
  neuen  Ländern.   Man  gibt
  ihnen so  einen Teil  ihrer
  Heimat zurück."
     -- Harald Schmidt in der
      Harald Schmidt-Show vom
                   20.06.1996
#Spaltenende
#Y+40
#C31
Telekommunikationsgesetz
#C21
Das neue TKG ............   1
