document.write ('<table width="100%" border="0"><tr><td valign="top"><table width="150" border="0" cellspacing="1" cellpadding="5">',
'<tr><td align="center"><BR>',
'<a href="../About/index.html"><IMG SRC="../GFX/1.png" alt="Колонка редакции" width="150" height="45" border="0"><BR>',
'<a href="../News/index.html"><IMG SRC="../GFX/2.png" alt="Амижные новости" width="150" height="31" border="0"></a><BR>',
'<a href="../Interview/index.html"><IMG SRC="../GFX/3.png" alt="Наши гости" width="150" height="29" border="0"></a><BR>',
'<a href="../History/index.html"><IMG SRC="../GFX/4.png" alt="Хроника событий" width="150" height="29" border="0"></a><BR>',
'<a href="../Focus/index.html"><IMG SRC="../GFX/5.png" alt="В фокусе" width="150" height="30" border="0"></a><BR>',
'<a href="../Exclusive/index.html"><IMG SRC="../GFX/6.png" alt="Xклюзив" width="150" height="29" border="0"></a><BR>',
'<a href="../Program/index.html"><IMG SRC="../GFX/7.png" alt="Программы и утилиты" width="150" height="27" border="0"><BR>',
'<a href="../Games/index.html"><IMG SRC="../GFX/8.png" alt="Игротека" width="150" height="29" border="0"></a><BR>',
'<a href="../Download/index.html"><IMG SRC="../GFX/9.png" alt="Download" width="150" height="43" border="0"></a><BR>',
'<BR><BR>',
'<IMG SRC="../GFX/0.gif" width="135" height="33" border="0"><BR>',
'<IMG SRC="../GFX/nopiracy.gif" alt="Мы против пиратства !" width="100" height="100" border="0"><BR>',
'<IMG SRC="../GFX/10.gif" width="135" height="22" border="0"></td></tr>',
'</td></table><td valign="top"><BR><BR>')
