(*
 *	This file was automaticly generated by OBumpRev 0.4.
 *	DO NOT EDIT THIS FILE!
 *)

<* STANDARD- *> <* INITIALISE- *> <* MAIN- *>

MODULE	jgrepRev;

IMPORT	SYSTEM;

CONST	version	*= 1;
	revision*= 0;
	date	*= "11.11.95";
	vers	*= "jgrep 1.0";
	vString	*= "jgrep 1.0 (11.11.95)\r\n";
	versTag	*= "$VER: jgrep 1.0 (11.11.95)\r\n";

BEGIN	(* Make sure that version string is visible *)
	SYSTEM.PUTREG (0, SYSTEM.ADR (versTag))
END	jgrepRev.
