document.write ('<td bgcolor="black" background="gfx/back.png" valign="top" width="155">',
'<table width="155" height="720" border="0" cellspacing="0" cellpadding="0" bgcolor="black">',
'<tr><td align="center" bgcolor="grey" background="gfx/left.png">',
'<p align="center"><font size="2"><a href="http://www.amiga.org.ru/"><img src="gfx/page/amiorg.jpg" alt="Amiga Information Center" width="100" height="30" border="0"><br>www.amiga.org.ru</a><br><br>',
'<a href="http://www.amirus.org.ru/"><img src="gfx/page/amirus.jpg" alt="AmiRus" width="100" height="30" border="0"><br>www.amirus.org.ru</a><br><br>',
'<a href="http://www.dihalt.org.ru/"><img src="gfx/page/dihalt.png" alt="DiHalt" width="100" height="30" border="0"><br>www.dihalt.org.ru</a><br><br>',
'<a href="http://www.pegasos.org.ru/"><img src="gfx/page/pegasosru.jpg" alt="Pegasos" width="100" height="30" border="0"><br>www.pegasos.org.ru</a><br><br>',
'<a href="http://www.aminet.net/"><img src="gfx/page/aminet.jpg" alt="AMInet" width="100" height="30" border="0"><br>www.aminet.net</a><br><br>',
'<a href="http://www.amiga.org/"><img src="gfx/page/amigaorg.jpg" alt="Amiga.Org" width="100" height="30" border="0"><br>www.amiga.org</a><br><br>',
'<a href="http://www.amigaworld.net/"><img src="gfx/page/amigaworld.gif" alt="AmigaWorld" width="100" height="30" border="0"><br>www.amigaworld.net</a><br><br>',
'<a href="http://www.amiga-news.de/en/"><img src="gfx/page/amiganewsde.jpg" alt="Amiga-News" width="100" height="30" border="0"><br>www.amiga-news.de</a><br><br>',
'<a href="http://www.morphos-news.de/"><img src="gfx/page/morphosnews.jpg" alt="MorphOS-News" width="100" height="30" border="0"><br>www.morphos-news.de</a><br><br>',
'<a href="http://www.morphzone.org/"><img src="gfx/page/morphzone.jpg" alt="MorphZone" width="100" height="30" border="0"><br>www.morphzone.net</a>',
'</p></font></table>',
'<br></td></table></td></table>',
'<table width="800" align="center" border="0" cellspacing="0" cellpadding="10"><tr>',
'<td bgcolor="black" background="gfx/back.png" valign="top">',
'<font size="-2" color="white"><b><img src="gfx/page/nopiracy.gif" alt="Мы против пиратства!" width="100" height="100" border="0" align="left">Copyright © 2002-2008 team Dogma - Until the End of Time!<br>All Rights Reserved. Все права защищены.</b><BR><BR>',
'Полное или частичное воспроизведение материалов или графики в любом виде и форме разрешается только с письменного разрешения редакции.<BR>',
'Amiga®, AmigaOS® & Boing® зарегистрированные торговые марки <a href="http://www.amiga.com/">Amiga Inc.</a>, Ravensdale, WA US.<BR>',
'Pegasos® & MorphOS® зарегистрированные торговые марки <a href="http://www.genesi.lu/">Genesi S.а.r.l.</a><BR>',
'<b>Amiga & Pegasos Rules Forever ! Back for the Future !</b></font>',
'</td></tr></table>')
