document.write ('<div class="wrapper"><a href="../index.html"><img src="../pix/main/dogma_logo.png" alt="Dogma#13" id="logo"/></a><div id="navwrap"><span class="nav_top"></span><ul id="menu-pages" class="nav superfish">',
'<li><a href="../about/index.html"><img src="../pix/main/omnom.png" title="Колонка редакции" width="20" height="20" /><span> Редакция</span></a>',
'<ul class="sub-menu">',
'<li><a href="../about/intro.htm"><span> От редакции</span></a>',
'<li><a href="../about/author.htm"><span> Авторы журнала</span></a></ul></li>',
'<li><a href="http://www.amiga.org.ru/forum/viewtopic.php?f=15&t=606" target="_blank"><img src="../pix/main/5.png" title="Наш форум" width="20" height="20" /><span> Форум</span></a></li>',
'<li><a href="../interview/index.html"><img src="../pix/main/2.png" title="Наши гости" width="20" height="20" /><span> Гости</span></a>',
'<ul class="sub-menu">',
'<li><a href="../interview/index.html"><span> Steven Solie & QT</span></a>',

'<ul class="sub-menu">',
'<li><a href="../interview/steven_solie_2.htm"><span> Steven Solie<br>(ComputerWorld)</span></a>',
'<li><a href="../interview/steven_solie_irc.htm"><span> Steven Solie<br>(irc#Ashachat)</span></a>',
'<li><a href="../interview/alfkil.htm"><span> Thorbjorn Wennermark (QT)</span></a>',
'<li><a href="../interview/julian_gollop.htm"><span> Julian Gollop</span></a>',
'<li><a href="../interview/andreas_magerl.htm"><span> Andreas Magerl</span></a>',
'<li><a href="../interview/mawi.htm"><span> Mad Wizards</span></a>',
'</ul>',

'<li><a href="../interview/index1.html"><span> Trevor Dickinson</span></a>',

'<ul class="sub-menu">',
'<li><a href="../interview/trevor_dickinson_blog.htm"><span> Trevor Dickinson Blog</span></a>',
'<li><a href="../interview/trevor_dickinson_amimania.htm"><span> Trevor Dickinson<br>(Amiga Mania)</span></a>',
'<li><a href="../interview/trevor_dickinson_micromart.htm"><span> Trevor Dickinson<br>(Micro Mart)</span></a>',
'<li><a href="../interview/trevor_dickinson_obligement.htm"><span> Trevor Dickinson<br>(Obligement)</span></a>',
'</ul>',

'<li><a href="../interview/index2.html"><span> team MorphOS & 3D</span></a>',

'<ul class="sub-menu">',
'<li><a href="../interview/richard_costello.htm"><span> Richard Costello<br>(Mortal Kombat)</span></a>',
'<li><a href="../interview/andy_broad.htm"><span> Andy Broad<br>(Blender 3D)</span></a>',
'<li><a href="../interview/jacaDcaps.htm"><span> Jacek Piszczek</span></a>',
'<li><a href="../interview/grzegorz_kraszewski.htm"><span> Grzegorz Kraszewski</span></a>',
'<li><a href="../interview/ilkka_lehtoranta.htm"><span> Ilkka Lehtoranta</span></a>',
'<li><a href="../interview/guillaume_boesel.htm"><span> Guillaume Boesel</span></a>',
'</ul>',

'</li></ul>',

'<li><a href="../history/index.html"><img src="../pix/main/3.png" title="Хроника событий" width="20" height="20" /><span> Хроника</span></a>',
'<ul class="sub-menu">',
'<li><a href="../history/expo2008.htm"><span> Colmar Expo 2008</span></a>',
'<li><a href="../history/amiparty12.htm"><span> AmiParty 2012</span></a>',
'<li><a href="../history/amiparty13.htm"><span> AmiParty 2013</span></a></ul></li>',
'<li><a href="../focus/index.html"><img src="../pix/main/4.png" title="В фокусе" width="20" height="20" /><span> В фокусе</span></a>',
'<ul class="sub-menu">',
'<li><a href="../focus/zorram.htm"><span> ZorRam</span></a>',
'<li><a href="../focus/replay.htm"><span> Replay</span></a>',
'<li><a href="../focus/retro_joystick_adapter.htm"><span> Retro Joystick Adapter</span></a>',
'<li><a href="../focus/macmini_mos.htm"><span> MorphOS на MacMini G4</span></a></ul></li>',
'<li><a href="../utilities/index.html"><img src="../pix/main/6.png" title="Офисный пакет" width="20" height="20" /><span> Офис</span></a>',
'<ul class="sub-menu">',
'<li><a href="../utilities/index.html"><span> MorphOS & AROS</span></a>',

'<ul class="sub-menu">',
'<li><a href="../utilities/morphos30_31.htm"><span> MorphOS 3.0 - 3.1</span></a>',
'<li><a href="../utilities/morphos32.htm"><span> MorphOS 3.2</span></a>',
'<li><a href="../utilities/morphos33.htm"><span> MorphOS 3.3</span></a>',
'<li><a href="../utilities/odyssey.htm"><span> Odyssey Browser 1.20</span></a>',
'<li><a href="../utilities/wanderer.htm"><span> Wanderer 1.2</span></a>',
'</ul>',

'<li><a href="../utilities/index1.html"><span> AmigaOS & DOpus</span></a>',

'<ul class="sub-menu">',
'<li><a href="../utilities/amigaos415.htm"><span> AmigaOS 4.1.5</span></a>',
'<li><a href="../utilities/amigaos416.htm"><span> AmigaOS 4.1.6 - 4.2</span></a>',
'<li><a href="../utilities/timberwolf.htm"><span> Timberwolf 4 RC1</span></a>',
'<li><a href="../utilities/classic_aos4.htm"><span> AmigaOS4 под классику</span></a>',
'<li><a href="../utilities/dopus5_x1000.htm"><span> DOPUS 5.9 II на x1000</span></a>',
'</ul>',

'<li><a href="../utilities/index2.html"><span> UAE & SOFT</span></a>',

'<ul class="sub-menu">',
'<li><a href="../utilities/fs_uae.htm"><span> FS-UAE 2.1.23</span></a>',
'<li><a href="../utilities/browser_os4.htm"><span> WWW для AmigaOS 4.1</span></a>',
'<li><a href="../utilities/wifios4.htm"><span> Wi-Fi в AmigaOS 4.x</span></a>',
'<li><a href="../utilities/afaos4.htm"><span> AfaOS 4.x</span></a>',
'<li><a href="../utilities/amiga_writer.htm"><span> AmigaWriter 2.2</span></a></ul></li>',
'</ul>',

'<li><a href="../games/index.html"><img src="../pix/main/cannon_fodder.png" title="Игротека" width="20" height="20" /><span> Игротека</span></a>',
'<ul class="sub-menu">',
'<li><a href="../games/cannon_fodder.htm"><span> Cannon Fodder</span></a></li>',
'<li><a href="../games/fullwin_3d.htm"><span> FullWin 3D</span></a></li>',
'<li><a href="../games/gollop.htm"><span> Братья Gollop</span></a>',
'<li><a href="../games/index.html"><span> Terramex</span></a></ul></li>',
'<li><a href="../download/index.html"><img src="../pix/main/boing.png" title="Архивы номеров" width="20" height="20" /><span> Архив</span></a></li>',
'</ul>',
'<a href="index.html#" id="mobile_nav" class="closed">Меню навигации<span></span></a><br class="clear" />',
'<span class="nav_bottom"></span>',
'</div>')
