document.write ('<div id="sidebar"><div class="widget"><a href="https://www.facebook.com/amiga.team.dogma" target="_blank"><img src="../pix/main/facebook.png" title="Мы в Facebook!" width="32" height="32" /></a> <a href="https://twitter.com/team_dogma" target="_blank"><img src="../pix/main/twitter.png" title="Мы в Twitter!" width="32" height="32" /></a> <a href="http://www.google.com.ua/translate?u='+encodeURIComponent(location.href)+'&langpair=ru%7Cuk&uk=ru&ie=UTF8" target="_blank"><img src="../pix/main/ukraine.png" alt="" width="32" height="32" /></a> <a href="http://www.google.com.ua/translate?u='+encodeURIComponent(location.href)+'&langpair=ru%7Cen&en=ru&ie=UTF8" target="_blank"><img src="../pix/main/english.png" alt="" width="32" height="32" /></a> <a href="http://www.google.com.ua/translate?u='+encodeURIComponent(location.href)+'&langpair=ru%7Cde&de=ru&ie=UTF8" target="_blank"><img src="../pix/main/germany.png" alt="" width="32" height="32" /></a></div><div class="widget"><h3>Наши друзья</h3>',	
'<table><tr><td align="justify"><img src="../pix/main/aic.png" alt="AiC" width="40" height="30" align="absmiddle" /></td><td align="justify"><a href="http://www.amiga.org.ru/" title="AiC" target="_blank"><h4> www.amiga.org.ru</h4></a></td></tr></table><small>Информационный центр амижников России и стран ближнего зарубежья. Новости, обсуждения, опросы мнений, статьи, полезные ссылки.</small><br><br>',
'<table><tr><td align="justify"><img src="../pix/main/morphos.png" alt="AmiRus" width="40" height="43" align="absmiddle" /></td><td align="justify"><a href="http://www.amirus.org.ru/" title="AmiRus" target="_blank"><h4>www.amirus.org.ru</h4></a></td></tr></table><small>Русская группа пользователей операционной системы MorphOS. Новости проекта, архив файлов.</small><br><br>',
'<table><tr><td align="justify"><img src="../pix/main/blog_boing.png" alt="AmiWiki" width="40" height="40" align="absmiddle" /></td><td align="justify"><a href="http://amiwiki.spb.ru/wiki/" title="AmiWiki" target="_blank"><h4>www.amiwiki.spb.ru</h4></a></td></tr></table><small>Русская википедия, посвященная компьютерам Commodore Amiga.</small><br><br>',
'<table><tr><td align="justify"><img src="../pix/main/dh_logo.png" alt="AmiWiki" width="46" height="29" align="absmiddle" /></td><td align="justify"><a href="http://www.dihalt.org.ru/" title="DiHalt!" target="_blank"><h4>www.dihalt.org.ru</h4></a></td></tr></table><small>Официальный сайт фестиваля компьютерного искусства DiHalt demoparty. Кибер-искусство в чистом виде!</small>',
'</div> <!-- end .widget -->',
'<div class="widget"><h3>Сегодня в номере</h3><ul>',
'<li><a href="../about/index.html">Колонка редакции</a></li>',
'<li><a href="http://www.amiga.org.ru/forum/viewtopic.php?f=15&t=606&st=0&sk=t&sd=a&start=105" target="_blank">Наш форум</a></li>',
'<li><a href="../interview/index.html">Наши гости</a></li>',
'<li><a href="../history/index.html">Хроника событий</a></li>',
'<li><a href="../focus/index.html">В фокусе</a></li>',
'<li><a href="../utilities/index.html">Офисный пакет</a></li>',
'<li><a href="../games/index.html">Игротека</a></li>',
'<li><a href="../download/index.html">Архивы номеров</a></li></ul>',
'</div> <!-- end .widget -->',
'<div class="widget"><h3>Стоит посетить</h3>',
'<a href="http://obligement.free.fr/" target="_blank"><img class="dogma" src="../pix/main/logos/obligement.png" alt="Obligement" width="110" height="40" border="0"></a> ',
'<a href="http://www.amiga-news.de/" target="_blank"><img class="dogma" src="../pix/main/logos/amiga-news.png" alt="Amiga News DE" width="110" height="40" border="0"><br>',
'<a href="http://www.ppa.pl/" target="_blank"><img class="dogma" src="../pix/main/logos/ppa.png" alt="Polski Portal Amigowy" width="110" height="40" border="0"> ',
'<a href="http://morphos.pl/" target="_blank"><img class="dogma" src="../pix/main/logos/morphos.png" alt="MorphOS PL" width="110" height="40" border="0"><br>',
'<a href="http://www.amiga.org/" target="_blank"><img class="dogma" src="../pix/main/logos/amiga.png" alt="Amiga Org" width="110" height="40" border="0"> ',
'<a href="http://www.amigaworld.net/" target="_blank"><img class="dogma" src="../pix/main/logos/amigaworld.png" alt="AmigaWorld Net" width="110" height="40" border="0">',
'</div> <!-- end .widget -->',
'<div class="widget"><h3>Мы в интернете </h3>')
